name: nnunetv2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - acvl-utils==0.2.5
      - argparse==1.4.0
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - blosc2==3.7.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - connected-components-3d==3.24.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dynamic-network-architectures==0.4.2
      - einops==0.8.1
      - fft-conv-pytorch==1.2.0
      - filelock==3.18.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - future==1.0.0
      - graphviz==0.21
      - hf-xet==1.1.7
      - hiddenlayer==0.2
      - huggingface-hub==0.34.4
      - idna==3.10
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - linecache2==1.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - ndindex==1.10.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - nnunetv2==2.6.2
      - numexpr==2.11.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - pip==25.2
      - platformdirs==4.3.8
      - py-cpuinfo==9.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - setuptools==80.9.0
      - simpleitk==2.5.2
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.19
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - traceback2==1.4.0
      - triton==3.4.0
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - unittest2==1.1.0
      - urllib3==2.5.0
      - yacs==0.1.8
